---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: KiokuDB
no_index:
  directory:
    - t
    - inc
requires:
  Cache::Ref: 0.02
  Class::MOP: 0.94
  Data::Stream::Bulk: 0.08
  Data::UUID: 1.203
  Data::Visitor: 0.24
  Digest::SHA: 0
  Hash::Util::FieldHash::Compat: 0
  IO: 1.23
  JSON: 2.12
  JSON::XS: 2.231
  Module::Pluggable::Object: 0
  Moose: 1.17
  MooseX::Clone: 0.04
  MooseX::Role::Parameterized: 0.1
  MooseX::YAML: 0.04
  PadWalker: 1.9
  Path::Class: 0
  Scalar::Util: 0
  Scope::Guard: 0
  Search::GIN: 0.03
  Set::Object: 1.26
  Storable: 0
  Task::Weaken: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::use::ok: 0
  Throwable: 0
  Tie::ToObject: 0
  Try::Tiny: 0
  YAML::XS: 0.3
  namespace::clean: 0.08
version: 0.54
