--- #YAML:1.0
name:               KiokuDB
version:            0.15
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::Cmd:             0.202
    Class::MOP:           0.73
    Data::Stream::Bulk:   0.03
    Data::UUID::LibUUID:  0
    Data::Visitor:        0.20
    Hash::Util::FieldHash::Compat:  0
    IO:                   1.2301
    JSON:                 2.12
    Module::Pluggable::Object:  0
    Moose:                0.63
    MooseX::App::Cmd:     0
    MooseX::Getopt:       0
    MooseX::Types::Path::Class:  0
    MooseX::YAML:         0.02
    namespace::clean:     0.08
    Path::Class:          0
    Scalar::Util:         0
    Scope::Guard:         0
    Search::GIN:          0.03
    Set::Object:          1.26
    Storable:             0
    Task::Weaken:         0
    Test::Exception:      0
    Test::More:           0
    Test::use::ok:        0
    Tie::ToObject:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
