--- #YAML:1.0
name:               KiokuDB
version:            0.30
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Stream::Bulk:   0.05
    Data::UUID::LibUUID:  0
    Data::Visitor:        0.24
    Digest::SHA:          0
    Hash::Util::FieldHash::Compat:  0
    IO:                   1.23
    JSON:                 2.12
    JSON::XS:             2.231
    KiokuDB::Cmd:         0.01
    Module::Pluggable::Object:  0
    Moose:                0.83
    MooseX::Clone:        0.04
    MooseX::Role::Parameterized:  0.1
    MooseX::YAML:         0.02
    namespace::clean:     0.08
    PadWalker:            1.9
    Path::Class:          0
    Scalar::Util:         0
    Scope::Guard:         0
    Search::GIN:          0.03
    Set::Object:          1.26
    Storable:             0
    Task::Weaken:         0
    Test::Exception:      0
    Test::More:           0
    Test::use::ok:        0
    Tie::ToObject:        0
    YAML::XS:             0.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
